# Generated by Django 2.2.4 on 2023-04-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_with_regestration', '0002_auto_20230404_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
