# Generated by Django 2.2.4 on 2023-04-04 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_with_regestration', '0003_auto_20230404_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourmessage',
            name='user_group',
        ),
        migrations.AddField(
            model_name='ourmessage',
            name='user_group1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chat_groups1', to='login_with_regestration.User'),
        ),
        migrations.AddField(
            model_name='ourmessage',
            name='user_group2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chat_groups2', to='login_with_regestration.User'),
        ),
    ]
