# Generated by Django 2.2.4 on 2023-04-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_with_regestration', '0003_post_likes_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likepost',
            unique_together={('user_who_like', 'post')},
        ),
    ]
