# Generated by Django 2.2.4 on 2023-04-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_with_regestration', '0003_comment_friendship_likecomment_likepost_message_ourmessage_post_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(null=True),
        ),
    ]
